spring:
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/spring_security_examples
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create



#spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:db
#  jpa:
#    hibernate:
#      ddl-auto: create
